version: "2.1"

services:
  init-certs:
    image: docker.io/bitnamilegacy/kafka:3.9
    command: /tmp/generate.sh
    working_dir: /tmp/
    user: 0:0
    volumes:
      - ./certs/:/tmp/certs/
      - "./generate.sh:/tmp/generate.sh"
  kafka:
    image: docker.io/bitnamilegacy/kafka:3.9
    container_name: kafka
    depends_on:
      init-certs:
        condition: service_completed_successfully
    ports:
      - "9093:9093"
      - "9095:9095"
    volumes:
      - "kafka_data:/bitnami"
      - ./certs/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks
      - ./certs/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9094",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - KAFKA_CFG_NODE_ID=1001
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1001@localhost:9096
      # Listeners
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9093,SASL_PLAINTEXT://:9095,PLAINTEXT://:9094,CONTROLLER://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://localhost:9093,SASL_PLAINTEXT://localhost:9095,PLAINTEXT://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,SSL:SSL,CONTROLLER:PLAINTEXT
      # Inter broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      # Security
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      - KAFKA_CLIENT_USERS=user,admin
      - KAFKA_CLIENT_PASSWORDS=pass,admin
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=supersecret
      - KAFKA_CFG_SSL_KEY_PASSWORD=supersecret
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=supersecret
      - KAFKA_CFG_SSL_CLIENT_AUTH=required

volumes:
  kafka_data:
    driver: local
