version: "2.1"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2182:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  init-certs:
      image: docker.io/bitnami/kafka:3.6
      command: /tmp/generate.sh
      working_dir: /tmp/
      user: 0:0
      volumes:
        - ./certs/:/tmp/certs/
        - "./generate.sh:/tmp/generate.sh"
  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
      init-certs:
        condition: service_completed_successfully
    ports:
      - "9093:9093"
      - "9095:9095"
    volumes:
      - "kafka_data:/bitnami"
      - ./certs/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks
      - ./certs/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks
    environment:
      # Zookeeper
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Listeners
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9093,SASL_PLAINTEXT://:9095,PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://localhost:9093,SASL_PLAINTEXT://localhost:9095,PLAINTEXT://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,SSL:SSL
      # Inter broker
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      # Security
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
      - KAFKA_CLIENT_USERS=user,admin
      - KAFKA_CLIENT_PASSWORDS=pass,admin
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=supersecret
      - KAFKA_CFG_SSL_KEY_PASSWORD=supersecret
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=supersecret
      - KAFKA_CFG_SSL_CLIENT_AUTH=required

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
