pipelines:
  file_socket_tcp:
    input:
      type: file
      persistence_mode: async
      watching_dir: SOME_DIR
      offsets_file: SOME_FILE
      offsets_op: reset
    output:
      type: socket
      network: SOME_NETWORK
      address: SOME_ADDRESS