version: "2"
run:
  build-tags:
    - e2e
    - fuzz
linters:
  default: none
  enable:
    - dogsled
    - dupl
    - errcheck
    - forbidigo
    - goconst
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    dupl:
      threshold: 120
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - whyNoLint
        - commentFormatting
        - paramTypeCombine
        - ptrToRefParam
        - unnamedResult
        - sprintfQuotedString
        - tooManyResultsChecker
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G304
    govet:
      enable:
        - composites
      disable:
        - printf
    misspell:
      locale: US
    staticcheck:
      checks:
        - -ST1021
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - govet
        text: declaration of "(err|ctx)"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
