linters-settings:
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 120
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - commentFormatting # insane-doc syntax requires "//>" format
      - paramTypeCombine
      - ptrToRefParam
      - unnamedResult
      - sprintfQuotedString
  gosec:
    excludes:
      - G304 # Potential file inclusion via variable -- it's ok for this project
  stylecheck:
    checks:
      - '-ST1021' # insane-doc syntax requires "//>" format

linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # Do not enable:
    # - wsl (too opinionated about newlines)
    # - godox (todos are OK)
    # - bodyclose (false positives on helper functions)
    # - prealloc  (not worth it in scope of this project)
    # - maligned  (same as prealloc)
    # - funlen (gocyclo is enough)
    # - gochecknoglobals (we know when it is ok to use globals)
    # - gochecknoinits (we know when it is ok to use inits)
    # - gosec
    # - lll
    # - revive

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude go:generate from lll
    - source: "//go:generate"
      linters: [ lll ]

    # Exclude links from lll
    - source: "// See https://"
      linters: [ lll ]

    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - gocognit
        - scopelint
        - lll

    # Ignore shadowing of err.
    - linters: [ govet ]
      text: 'declaration of "(err|ctx)"'

    # Ignore linters in main packages.
    - path: cmd\/file\.d\.go
      linters: [ gocognit, gocyclo ]

run:
  build-tags:
    - e2e
    - fuzz
    - linux
