before:
  hooks:
    - go mod download
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
release:
  prerelease: auto

builds:
  - main: ./cmd/file.d
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -pgo=default.pgo
    ldflags:
      - -X github.com/ozontech/file.d/buildinfo.Version={{.Version}}
nfpms:
  - 
    maintainer: Vitkovskiy Vladimir <vvitkovskiy@ozon.ru>
    formats:
      - deb
      - rpm
    recommends:
      - systemd
    description: |- 
      file.d is a tool for building data pipelines: 
      read, process and output events.
    homepage: https://ozontech.github.io/file.d/
    vendor: Ozon Tech
    bindir: /usr/bin
    contents: 
      - src: ./releaser/config.yaml
        dst: /etc/file.d/config.yaml
        type: config
      - src: ./releaser/file.d.service
        dst: /etc/systemd/system/file.d.service
