networks:
  network_redis_cluster:
    driver: bridge

services:
  redis-base:
    image: redis:latest
    container_name: redis-base
    ports:
      - 6380:6379

  redis-ring-1:
    image: redis:latest
    container_name: redis-ring-1
    ports:
      - 6381:6379
  redis-ring-2:
    image: redis:latest
    container_name: redis-ring-2
    ports:
      - 6382:6379

  redis-single-node-cluster:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-single-node-cluster
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
    ports:
      - 6379:6379
