# https://github.com/elastic/start-local/tree/main
services:
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: es-local-test
    ports:
      - "19200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --head --fail -u elastic:elastic http://elasticsearch:19200",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
