pipelines:
  file_es_split:
    input:
      type: file
    output:
      type: elasticsearch
      batch_flush_timeout: 200ms
      batch_size: 500 * 1
      connection_timeout: 30s
      endpoints:
        - http://localhost:9200
      fatal_on_failed_insert: true
      split_batch: true
      strict: false
      index_format: index_name
      workers_count: 1
