version: "2"

services:
  zookeeper:
    image: zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/data"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
  kafka:
    image: docker.io/bitnamilegacy/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
