// Code generated by "stringer -type Condition -trimprefix Condition"; DO NOT EDIT.

package antispam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConditionPrefix-0]
	_ = x[ConditionContains-1]
	_ = x[ConditionSuffix-2]
}

const _Condition_name = "PrefixContainsSuffix"

var _Condition_index = [...]uint8{0, 6, 14, 20}

func (i Condition) String() string {
	if i >= Condition(len(_Condition_index)-1) {
		return "Condition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Condition_name[_Condition_index[i]:_Condition_index[i+1]]
}
