{{- if eq "Deployment" .Values.resourceType }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "filed.fullname" . }}
  labels:
    {{- include "filed.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "filed.selectorLabels" . | nindent 4 }}
{{- end }}
