pipelines:
  test_pipeline:
    input:
      type: file
      persistence_mode: async
      watching_dir: ./_mydata
      filename_pattern: "welcome.json"
      offsets_file: ./_mydata/offsets.yaml
    actions:
      - type: rename
        override: true
        systemd\.unit: service
        syslog\.identifier: service
        k8s_pod_label_app: service
      - type: discard
        do_if:
          op: equal
          field: service
          values: [null, ""]
    output:
      type: stdout
