{
 "title": "File.d Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(file_d_file_d_version,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(file_d_file_d_version{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "pipeline",
    "label": "Pipeline",
    "query": {
     "query": "{__name__=~\"file_d_pipeline_.*_antispam_active\", job=\"$job\", instance=~\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "description": "Displays the File.d version for the selected instance. When 'All' is selected, lists all detected versions.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (instance, version) (file_d_file_d_version{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: {{version}}"
    }
   ]
  },
  {
   "title": "Logs size [1d]",
   "type": "stat",
   "description": "Amount of logs written by File.d in bytes.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(file_d_pipeline_${pipeline}_output_plugin_events_size_total{job=\"$job\", instance=~\"$instance\"}[24h]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Displays the average uptime of all selected File.d instances in 'd hh:mm:ss format'. When 'All' is selected, shows the shortest (most recently restarted) uptime.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(min by () ((time() - process_start_time_seconds{job=\"$job\", instance=~\"$instance\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Logs rate by size",
   "type": "timeseries",
   "description": "Amount of logs consumed by File.d in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(file_d_pipeline_${pipeline}_output_plugin_events_size_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Logs rate by count",
   "type": "timeseries",
   "description": "Amount of logs consumed by File.d in count per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(file_d_pipeline_${pipeline}_input_plugin_events_count_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Antispam",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Antispam active",
     "type": "timeseries",
     "description": "Indicator whether there are banned sources or not.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "file_d_pipeline_${pipeline}_antispam_active{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Antispam banned",
     "type": "timeseries",
     "description": "Banned sources by source_name. For file or k8s input plugin source_name is filename.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "sum(file_d_pipeline_${pipeline}_antispam_banned{job=\"$job\", instance=~\"$instance\"}) by (source_name) > 0",
       "legendFormat": "{{source_name}}"
      }
     ]
    },
    {
     "title": "Antispam exceptions",
     "type": "timeseries",
     "description": "Rate of antispam exceptions applied by exception name from File.d config. Antispam exceptions are never banned.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(file_d_pipeline_${pipeline}_antispam_exceptions_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process open FDs",
     "type": "timeseries",
     "description": "Amount of open file descriptors processed by File.d.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process deleted FDs",
     "type": "timeseries",
     "description": "Amount of open file descriptors of deleted files processed by File.d. If deleted file descriptors grow it means that File.d cannot process all of the events fast enough.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "process_deleted_fds{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Event pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg In Use Events by instance",
     "type": "timeseries",
     "description": "Amount of events currently in use. If the value is the same as event pool capacity, it means that all events are busy and there are no free events to process new logs.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "file_d_pipeline_${pipeline}_event_pool_in_use_events{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(avg_over_time(file_d_pipeline_${pipeline}_event_pool_in_use_events{job=\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Latency 99p",
     "type": "timeseries",
     "description": "Amount of time for getting events from the event pool.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, max(rate(file_d_pipeline_${pipeline}_event_pool_latency_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le))",
       "legendFormat": "Sum"
      },
      {
       "expr": "histogram_quantile(0.99, max(rate(file_d_pipeline_${pipeline}_event_pool_latency_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs done rate",
     "type": "timeseries",
     "description": "Amount of output write jobs completed. There are two types of jobs:\n1) Finished by timeout\n2) Finished by batch max size exceeded.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(rate(file_d_pipeline_${pipeline}_batcher_jobs_done_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{status}}"
      },
      {
       "expr": "sum(rate(file_d_pipeline_${pipeline}_batcher_jobs_done_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Avg batches in progress ",
     "type": "timeseries",
     "description": "Average amount of batches in process of sending to output.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "sum(avg_over_time(file_d_pipeline_${pipeline}_batcher_workers_in_progress{job=\"$job\", instance=~\"$instance\"}[$__interval])) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(avg_over_time(file_d_pipeline_${pipeline}_batcher_workers_in_progress{job=\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Output Latency",
     "type": "timeseries",
     "description": "Amount of time it takes to write events to the output.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg(rate(file_d_pipeline_${pipeline}_batcher_out_fn_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, instance))",
       "legendFormat": "99p {{ instance }}"
      },
      {
       "expr": "histogram_quantile(0.95, avg(rate(file_d_pipeline_${pipeline}_batcher_out_fn_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, instance))",
       "legendFormat": "95p {{ instance }}"
      }
     ]
    },
    {
     "title": "Waiting For Commit",
     "type": "timeseries",
     "description": "Amount of time spent in waiting for correct sequential batches commit. So if there are 3 batches, 3rd batch completed sending faster, it will wait for the first two batches to complete before committing to the input.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, avg(rate(file_d_pipeline_${pipeline}_batcher_commit_waiting_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, instance))",
       "legendFormat": "99p {{ instance }}"
      },
      {
       "expr": "histogram_quantile(0.95, avg(rate(file_d_pipeline_${pipeline}_batcher_commit_waiting_seconds_bucket{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (le, instance))",
       "legendFormat": "95p {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go runtime: CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Total user and system CPU time spent in seconds.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(process_cpu_seconds_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Process virtual memory",
     "type": "timeseries",
     "description": "Virtual memory size in bytes.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(process_virtual_memory_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Process resident memory",
     "type": "timeseries",
     "description": "Resident memory size in bytes. It reflects the amount of real physical memory used.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "sum(process_resident_memory_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Taken system memory",
     "type": "timeseries",
     "description": "How many bytes of memory in total is taken from system by Go",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go runtime: Allocs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memstat heap objects",
     "type": "timeseries",
     "description": "Number of allocated objects.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_heap_objects{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(go_memstats_heap_objects{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "Allocated total",
     "type": "timeseries",
     "description": "Number of bytes allocated and still in use.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of allocated memory",
     "type": "timeseries",
     "description": "Total number of bytes allocated, even if freed.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}\n[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap allocated",
     "type": "timeseries",
     "description": "Number of heap bytes allocated and still in use.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap idle",
     "type": "timeseries",
     "description": "Shows how many bytes are in idle spans. Idle spans have no objects in them. These spans could be (and may already have been) returned to the OS, or they can be reused for heap allocations, or they can be reused as stack memory.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap released to OS",
     "type": "timeseries",
     "description": "Number of heap bytes released to OS.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap could be released",
     "type": "timeseries",
     "description": "How many bytes of memory could be released, but is kept by runtime, so that runtime can allocate objects on the heap without asking OS for more memory.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=~\"$instance\"} - go_memstats_heap_released_bytes{job=\"$job\", instance=~\"$instance\"}\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Stack in use",
     "type": "timeseries",
     "description": "Bytes of memory is used by stack memory spans, which have atleast one object in them.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mspan sys",
     "type": "timeseries",
     "description": "Bytes are obtained from OS for mspan structures.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"}\n",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "mspan in use",
     "type": "timeseries",
     "description": "Bytes are in use by mspan structures.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go runtime: GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GO GC runs per minute",
     "type": "timeseries",
     "description": "How many times Go's garbage collector runs per minute in File.d.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 60",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GO GC time per 5 minutes",
     "type": "timeseries",
     "description": "Total time spent in Go GC pauses over 5 minutes in File.d.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"$job\", instance=~\"$instance\"}[5m])) by (instance) * 300",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"$job\", instance=~\"$instance\"}[5m])) * 300",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "GO GC duration max",
     "type": "timeseries",
     "description": "A summary of the pause duration of garbage collection cycles.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"1\", job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(go_gc_duration_seconds{quantile=\"1\", job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Sum"
      }
     ]
    },
    {
     "title": "GO GC duration, 0.75q",
     "type": "timeseries",
     "description": "A summary of the pause duration of garbage collection cycles.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{quantile=\"0.75\", job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(go_gc_duration_seconds{quantile=\"0.75\", job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Go runtime: Concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Goroutines count",
     "type": "timeseries",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(go_goroutines{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Average trend"
      }
     ]
    },
    {
     "title": "Threads count",
     "type": "timeseries",
     "description": "Number of OS threads created.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "go_threads{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top 10 writers by size/count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top 10 size",
     "type": "timeseries",
     "description": "Top 10 writers by logs size. Change k8s_pod_label_app to your matching labels to get the correct info.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(file_d_pipeline_${pipeline}_input_events_size_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (k8s_pod_label_app))",
       "legendFormat": "{{ k8s_pod_label_app }}"
      }
     ]
    },
    {
     "title": "Top 10 count",
     "type": "timeseries",
     "description": "Top 10 writers by logs count. Change k8s_pod_label_app to your matching labels to get the correct info.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(file_d_pipeline_${pipeline}_input_events_count_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (k8s_pod_label_app))",
       "legendFormat": "{{ k8s_pod_label_app }}"
      }
     ]
    }
   ]
  }
 ]
}