version: "3"
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "9001:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
