# todo loki and grafana
services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: '0'
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: --config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./config.yaml:/etc/loki/config.yaml

